# Generated by Django 3.1 on 2020-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, null=True)),
                ('kcal', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('protien', models.FloatField()),
            ],
        ),
    ]
